set(SDLMIXER_VERSION 3.2.4)

set(SDLMIXER_INSTALL       OFF CACHE BOOL "" FORCE)
set(SDLMIXER_INSTALL_CPACK OFF CACHE BOOL "" FORCE)
set(SDLMIXER_INSTALL_MAN   OFF CACHE BOOL "" FORCE)
set(SDLMIXER_DEPS_SHARED   ON  CACHE BOOL "" FORCE)
set(SDLMIXER_EXAMPLES      OFF CACHE BOOL "" FORCE)
set(SDLMIXER_STRICT        ON  CACHE BOOL "" FORCE)
set(SDLMIXER_TESTS         OFF CACHE BOOL "" FORCE)
set(SDLMIXER_VENDORED      OFF CACHE BOOL "" FORCE)

# Filetype support.
set(SDLMIXER_AIFF              OFF CACHE BOOL "" FORCE)
set(SDLMIXER_AU                OFF CACHE BOOL "" FORCE)
set(SDLMIXER_FLAC              OFF CACHE BOOL "" FORCE)
set(SDLMIXER_GME               OFF CACHE BOOL "" FORCE)
set(SDLMIXER_MIDI              OFF CACHE BOOL "" FORCE)
set(SDLMIXER_MOD               ON  CACHE BOOL "" FORCE)
set(SDLMIXER_MOD_XMP           ON  CACHE BOOL "" FORCE)
set(SDLMIXER_MOD_XMP_LITE      ON  CACHE BOOL "" FORCE)
set(SDLMIXER_MP3               OFF CACHE BOOL "" FORCE)
set(SDLMIXER_OPUS              OFF CACHE BOOL "" FORCE)
set(SDLMIXER_VOC               OFF CACHE BOOL "" FORCE)
set(SDLMIXER_VORBIS_STB        OFF CACHE BOOL "" FORCE)
set(SDLMIXER_VORBIS_VORBISFILE OFF CACHE BOOL "" FORCE)
set(SDLMIXER_VORBIS_TREMOR     OFF CACHE BOOL "" FORCE)
set(SDLMIXER_WAV               ON  CACHE BOOL "" FORCE)
set(SDLMIXER_WAVPACK           OFF CACHE BOOL "" FORCE)

FetchContent_Declare(
    SDL3_Mixer
    URL https://github.com/libsdl-org/SDL_mixer/archive/refs/tags/release-${SDLMIXER_VERSION}.tar.gz
    OVERRIDE_FIND_PACKAGE
)
FetchContent_MakeAvailable(SDL3_Mixer)
