image: git.rayment.fr:5050/docker/docker-opengl:latest

stages:
  - build
  - test
  - coverage

build:
  stage: build
  script:
    - cd contrib && make && cd ..
    - make
  artifacts:
    paths:
      - build

test:
  stage: test
  script:
    - make test
    - cd test && sh test.sh && .. && sh tools/stats

coverage:
  stage: coverage
  script:
    - make coverage
    - lcov --list coverage.info
  coverage: Total:\|(\d+\.?\d+\%)

