image: git.rayment.fr:5050/docker/docker-opengl:latest

stages:
  - build
  - test

build:
  stage: build
  script:
    - cd contrib && make && cd ..
    - make
  artifacts:
    paths:
      - build

test:
  stage: test
  script:
    - make test
    - cd test && sh test.sh && .. && sh tools/stats

