#
# Makefile
#
# Author       : Finn Rayment <finn@rayment.fr>
# Date created : 29/03/2021
#

# DO NOT EDIT THIS FILE
# PLEASE MAKE ALL CHANGES IN THE SUPPLIED vars.mk INSTEAD
#

include vars.mk

export PREFIX?=/usr/local
export VERSION
export ARCH
export DEBUG?=0
export DEBUG_TRACE?=1
export SAVE_TEMPS?=0

export LIBNAME:=sticky

DISTFILES:=COPYING DOCUMENTATION INSTALL README Doxyfile Makefile vars.mk \
           sticky.sln sticky.vcxproj sticky.vcxproj.filters sticky.vcxproj.user
DISTDIRS:=contrib docs src include test tools

CC:=cc
LD:=$(CC)

CCFLAGS:=--std=c99
CXXFLAGS:=-Wall -Wextra -Werror --pedantic-errors \
          -fPIC -m$(ARCH) -O3 -DVERSION=\"${VERSION}\" \
          -fvisibility=hidden
LDFLAGS:=

ifeq ($(DEBUG),1)
CXXFLAGS+=-g -DDEBUG=1
ifneq ($(DEBUG_TRACE),0)
CXXFLAGS+=-DDEBUG_TRACE=$(DEBUG_TRACE)
endif
ifneq ($(DEBUG_ASAN),0)
CXXFLAGS+=-fsanitize=address
LDFLAGS+=-fsanitize=address
endif
ifneq ($(DEBUG_ANALYZE),0)
CXXFLAGS+=-fanalyzer
endif
else
CXXFLAGS+=-DNDEBUG -fomit-frame-pointer
endif

ifeq ($(SAVE_TEMPS),1)
CXXFLAGS+=-save-temps
endif

ifeq ($(ARCH),64)
CXXFLAGS+=-DSTICKY_64BIT=1
else
ifeq($(ARCH),32)
CXXFLAGS+=-DSTICKY_32BIT=1
endif

MAKE_CXXFLAGS:=-DSTICKY_ISMAKELIB=1
TEST_CXXFLAGS:=
TEST_LDFLAGS:=

LIBRARIES:=glew sdl2 freetype2

SOURCES:=$(wildcard src/*.c) $(wildcard src/*/*.c)
HEADERS:=$(shell find include/ -name '*.h') \
         $(shell find contrib/include/ -name '*.h')

# OS-dependant variables
ifeq ($(OS),Windows_NT)
	SOURCES:=$(filter-out $(wildcard src/*/**_posix.c),$(SOURCES))
	HEADERS:=$(filter-out $(wildcard include/sticky/*/**_posix.h),$(HEADERS))
	STATIC_LIB:=$(LIBNAME)-$(VERSION).lib
	LINK_LIB=$(LIBNAME).dll
	DYNAMIC_LIB:=$(LIBNAME)-$(VERSION).dll
else
	UNAME_S:=$(shell uname -s)
	SOURCES:=$(filter-out $(wildcard src/*/**_win32.c),$(SOURCES))
	HEADERS:=$(filter-out $(wildcard include/sticky/*/**_win32.h),$(HEADERS))
	ifeq ($(UNAME_S),Linux)
		OS:=Linux
		LIBRARIES+=openal
		CXXFLAGS+=-Wpedantic -D_POSIX_C_SOURCE=200112L
		LDFLAGS+=-pthread
		ifeq ($(ENABLE_OPENMP),1)
			CXXFLAGS+=-fopenmp -DENABLE_OPENMP=1
		endif
		TEST_LDFLAGS+=-Wl,-rpath,../build
		STATIC_LIB:=lib$(LIBNAME).a.$(VERSION)
		LINK_LIB=lib$(LIBNAME).so
		DYNAMIC_LIB:=$(LINK_LIB).$(VERSION)
	endif
	ifeq ($(UNAME_S),Darwin)
		OS:=Darwin
		CXXFLAGS+=-Wno-deprecated-declarations -Wno-typedef-redefinition \
		          -Wno-static-in-inline
		LDFLAGS+=-framework OpenGL -framework OpenAL -pthread
		ifeq ($(ENABLE_OPENMP),1)
			CXXFLAGS+=-Xpreprocessor -fopenmp -DENABLE_OPENMP=1
			LDFLAGS+=-lomp
		endif
		STATIC_LIB:=lib$(LIBNAME)-$(VERSION).a
		LINK_LIB=lib$(LIBNAME).dylib
		DYNAMIC_LIB:=lib$(LIBNAME)-$(VERSION).dylib
	endif
endif
export OS

ifeq ($(ENABLE_ASSIMP),1)
LIBRARIES+=assimp
CXXFLAGS+=-DENABLE_ASSIMP=1
endif

# remove memtrace utility if not debugging
ifneq ($(DEBUG),1)
SOURCES:=$(filter-out src/memory/memtrace.c,$(SOURCES))
HEADERS:=$(filter-out include/memory/memtrace.h,$(HEADERS))
endif

OBJECTS:=$(patsubst src/%,obj/%,\
         $(patsubst %.c,%.o,$(SOURCES)))
INCLUDE:=-Iinclude/ -Icontrib/include \
         $(shell pkg-config --cflags $(LIBRARIES)) \
         -DGL_GLEXT_PROTOTYPES

LDFLAGS+=$(shell pkg-config --libs $(LIBRARIES)) -lm
TEST_LDFLAGS+=-Lbuild/ -lsticky

TEST_INCLUDE:=-Itest/
TEST_SOURCES:=$(wildcard test/*.c) $(wildcard test/*/*.c)
TEST_OBJECTS:=$(patsubst %.c,%.o,$(TEST_SOURCES))
TEST_BINARIES:=$(patsubst %.c,%,$(TEST_SOURCES))

# create a build string
BUILD_STRING:=lib$(LIBNAME)-$(VERSION)
ifeq ($(DEBUG),1)
BUILD_STRING+=+debug
endif
ifneq ($(DEBUG_TRACE),0)
BUILD_STRING+=+trace($(DEBUG_TRACE))
endif
ifeq ($(ENABLE_ASSIMP),1)
BUILD_STRING+=+assimp
endif
ifeq ($(ENABLE_OPENMP),1)
BUILD_STRING+=+openmp
endif

all: vardump $(OBJECTS)
	@mkdir -p build
	@echo "Packaging objects into static library..."
	@ar -crv build/$(STATIC_LIB) $(OBJECTS)
	@ranlib build/$(STATIC_LIB)
	@echo "Linking objects into dynamic library..."
	@$(CC) $(OBJECTS) $(LDFLAGS) -shared -o build/$(DYNAMIC_LIB)
	@ln -fs $(DYNAMIC_LIB) build/$(LINK_LIB)
	@echo "$(BUILD_STRING)" > build/buildinfo
	@if [ "$(DEBUG)" = 0 ]; then \
		echo "Stripping symbols from library output..."; \
		if [ "$(OS)" == "Darwin" ]; then \
			strip -u -r -x build/$(STATIC_LIB) build/$(DYNAMIC_LIB); \
		else \
			strip --strip-unneeded build/$(STATIC_LIB) build/$(DYNAMIC_LIB); \
		fi \
	fi
	@echo "Compilation finished. Check build/ for output."

vardump:
	@echo "Makefile vars (build):"
	@echo "  CFLAGS   := $(CFLAGS)"
	@echo "  CXXFLAGS := $(CXXFLAGS)"
	@echo "  INCLUDE  := $(INCLUDE)"
	@echo "  LDFLAGS  := $(LDFLAGS)"

test_vardump:
	@echo "Makefile vars (test):"
	@echo "  CFLAGS   := $(CFLAGS)"
	@echo "  CXXFLAGS := $(CXXFLAGS)"
	@echo "  INCLUDE  := $(INCLUDE)"
	@echo "  LDFLAGS  := $(LDFLAGS)"
	@echo "  TEST_CXXFLAGS := $(TEST_CXXFLAGS)"
	@echo "  TEST_LDFLAGS  := $(TEST_LDFLAGS)"

obj/%.o: src/%.c
	@echo "Compiling src/$*.c"
	@mkdir -p $(shell dirname $@)
	@$(CC) $(CCFLAGS) $(CXXFLAGS) $(MAKE_CXXFLAGS) $(INCLUDE) -c $< -o $@

docs:
	@echo "Generating docs..."
	@doxygen Doxyfile

install:
	@echo "Installing $(PREFIX)/include/sticky"
	@install -d $(PREFIX)/include/sticky
	@cp -R include/* $(PREFIX)/include/
	@find $(PREFIX)/include/sticky -type d -print0 | xargs -0 chmod 755
	@echo "Installing $(PREFIX)/include/sticky.h"
	@find $(PREFIX)/include/sticky -type f -print0 | xargs -0 chmod 644
	@install -d $(PREFIX)/lib
	@echo "Installing $(PREFIX)/lib/$(LINK_LIB)"
	@cp -a -f build/$(LINK_LIB) $(PREFIX)/lib
	@echo "Installing $(PREFIX)/lib/$(DYNAMIC_LIB)"
	@install build/$(DYNAMIC_LIB) $(PREFIX)/lib
	@echo "Updating ldconfig cache..."
	@ldconfig || true

uninstall:
	@echo "Uninstalling $(PREFIX)/lib/$(LINK_LIB)"
	@rm -f $(PREFIX)/lib/$(LINK_LIB)
	@echo "Uninstalling $(PREFIX)/lib/$(DYNAMIC_LIB)"
	@rm -f $(PREFIX)/lib/$(DYNAMIC_LIB)
	@echo "Uninstalling $(PREFIX)/include/sticky"
	@rm -rf $(PREFIX)/include/sticky
	@echo "Uninstalling $(PREFIX)/include/sticky.h"
	@rm -rf $(PREFIX)/include/sticky.h

test: test_vardump $(TEST_OBJECTS) $(TEST_BINARIES)

test/%.o: test/%.c
	@echo "Compiling test/$*.c"
	@$(CC) -g $(CCFLAGS) $(CXXFLAGS) $(TEST_CXXFLAGS) \
		$(TEST_INCLUDE) $(INCLUDE) -c $< -o $@

test/%: test/%.o
	@echo "Linking test/$*.o"
	@$(LD) $< $(LDFLAGS) $(TEST_LDFLAGS) -o $@
	@# macOS compiler doesn't respect rpath the same way regular *nix does
	@if [ "$(OS)" = "Darwin" ]; then \
		install_name_tool \
			-change build/$(DYNAMIC_LIB) ../build/$(DYNAMIC_LIB) $@; \
	fi

dist:
	@echo "Calling \`make clean' functions to delete work prior to archival."
	@echo "You have 5 seconds to cancel the clean actions with Ctrl+C."
	@sleep 5
	@$(MAKE) clean
	@cd contrib && $(MAKE) clean && $(MAKE) purge
	@$(MAKE) clean_docs
	@echo "Packing code into archive..."
	@rm -rf lib$(LIBNAME)-$(VERSION)
	@mkdir -p lib$(LIBNAME)-$(VERSION)
	@cp -R $(DISTFILES) $(DISTDIRS) lib$(LIBNAME)-$(VERSION)
	@tar -cJf lib$(LIBNAME)-$(VERSION).tar.xz lib$(LIBNAME)-$(VERSION)
	@rm -rf lib$(LIBNAME)-$(VERSION)
	@echo "Archive 'lib$(LIBNAME)-$(VERSION).tar.xz' was created successfully."

clean:
	@echo "Cleaning objects and test files..."
	@rm -rf build/ obj/ $(BINARY) $(TEST_OBJECTS) $(TEST_BINARIES) || true

clean_test:
	@echo "Cleaning test files..."
	@rm -rf $(TEST_OBJECTS) $(TEST_BINARIES) || true

clean_docs:
	@echo "Cleaning doc files..."
	@rm -rf docs/html || true

.PHONY: all \
        test_vardump vardump \
        dist docs \
        install uninstall \
        test \
        clean clean_test clean_docs

