name: CI

on: [push, pull_request]

jobs:
  build-linux:
    name: Linux build
    runs-on: ubuntu-latest
    steps:
      - name: Install system packages
        run: |
          sudo apt-get update && \
          sudo apt-get install \
               libglew-dev libsdl2-dev libopenal-dev libassimp-dev \
               libfreetype6-dev libopengl-dev
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Compile contrib dependencies
        run: |
          cd contrib && make
      - name: Compile source
        run: |
          make
      - name: Compile tests
        run: |
          make test
      - name: Execute test suite
        run: |
          cd test && sh stats.sh && sh test.sh
  build-macos:
    name: macOS build
    runs-on: macos-latest
    steps:
      - name: Install system packages
        run: |
          brew update && \
          brew install \
            pkg-config glew sdl2 assimp freetype libomp
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Compile contrib dependencies
        run: |
          cd contrib && make
      - name: Compile source
        run: |
          make
      - name: Compile tests
        run: |
          make test
      - name: Execute test suite
        run: |
          cd test && sh stats.sh && sh test.sh
  build-windows-x86:
    name: Windows build (x86)
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
      - name: Compile contrib dependencies
        run: |
          cd contrib
          nmake /f Makefile.win
          cd ..
      - name: Compile source
        run: msbuild /p:Platform=Win32;Configuration=Release sticky.vcxproj

