name: CI

on: [push, pull_request]

jobs:
  build-linux:
    name: Linux build
    runs-on: ubuntu-latest
    steps:
      - name: Install system packages
        run: |
          sudo apt-get update && \
          sudo apt-get install \
               libglew-dev libsdl2-dev libopenal-dev libassimp-dev \
               libfreetype6-dev libopengl-dev
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Compile contrib dependencies
        run: |
          cd contrib && make
      - name: Compile source
        run: |
          make
      - name: Compile tests
        run: |
          make test
      - name: Execute test suite
        run: |
          cd test && sh test.sh && cd .. && sh tools/stats
  build-macos:
    name: macOS build
    runs-on: macos-latest
    steps:
      - name: Install system packages
        run: |
          brew update && \
          brew install \
            pkg-config glew sdl2 assimp freetype libomp
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Compile contrib dependencies
        run: |
          cd contrib && make
      - name: Compile source
        run: |
          make
      - name: Compile tests
        run: |
          make test
      - name: Execute test suite
        run: |
          cd test && sh test.sh && cd .. && sh tools/stats
  build-windows-x86:
    name: Windows build (x86)
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
      - name: Add nmake to PATH
        uses: ilammy/msvc-dev-cmd@v1
      - name: Cache contrib dependencies
        id: cache-contrib
        uses: actions/cache@v3
        with:
          path: |
            ./contrib/include/
            ./contrib/lib32
            ./contrib/lib64
          key: ${{ runner.os }}-contrib-${{ hashFiles('vars.mk') }}
      - name: Compile contrib dependencies
        if: steps.cache-contrib.outputs.cache-hit != 'true'
        run: |
          cd contrib
          nmake /f Makefile.win
          cd ..
      - name: Compile source
        run: msbuild /p:"Platform=Win32;Configuration=Release" sticky.vcxproj
  build-windows-x64:
    name: Windows build (x64)
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
      - name: Add nmake to PATH
        uses: ilammy/msvc-dev-cmd@v1
      - name: Cache contrib dependencies
        id: cache-contrib
        uses: actions/cache@v3
        with:
          path: |
            ./contrib/include/
            ./contrib/lib32
            ./contrib/lib64
          key: ${{ runner.os }}-contrib-${{ hashFiles('vars.mk') }}
      - name: Compile contrib dependencies
        if: steps.cache-contrib.outputs.cache-hit != 'true'
        run: |
          cd contrib
          nmake /f Makefile.win
          cd ..
      - name: Compile source
        run: msbuild /p:"Platform=x64;Configuration=Release" sticky.vcxproj

